name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  job_id:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd auth && docker build -t chrishj59/auth .
        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
          env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}} 
        - run: docker push chrishj59/auth
        
        
      
